spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.c98s2k0k8maj.ap-northeast-2.rds.amazonaws.com:3306/etime
    username: admin1
    password: Password1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[show_sql]": true
        "[format_sql]": true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB
logging:
  level:
    org:
      springframework:
        security:
          web: trace
eruo:
  v1:
    upload:
      path: upload


